const weddingDate=new Date('2026-08-14T16:00:00+03:00');const units={days:document.querySelector('#days'),hours:document.querySelector('#hours'),minutes:document.querySelector('#minutes'),seconds:document.querySelector('#seconds')};
function updateCountdown(){const d=Math.max(0,weddingDate-new Date()),v={days:Math.floor(d/86400000),hours:Math.floor(d/3600000%24),minutes:Math.floor(d/60000%60),seconds:Math.floor(d/1000%60)};Object.entries(v).forEach(([k,n])=>units[k].textContent=k==='days'?String(n):String(n).padStart(2,'0'))}updateCountdown();setInterval(updateCountdown,1000);
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const heroBg=document.querySelector('.hero-bg');addEventListener('scroll',()=>{if(scrollY<innerHeight)heroBg.style.transform=`translateY(${scrollY*.15}px) scale(1.05)`},{passive:true});
let player,musicPlaying=false,musicRequested=true;const musicButton=document.querySelector('#music-toggle');window.onYouTubeIframeAPIReady=()=>{player=new YT.Player('youtube-player',{height:'1',width:'1',videoId:'bEO_1oA2ZDs',playerVars:{playsinline:1,controls:0,loop:1,playlist:'bEO_1oA2ZDs'},events:{onReady:()=>{player.playVideo();musicPlaying=true;musicButton.classList.remove('paused');musicButton.querySelector('span').textContent='♫  Музыка играет'}}})};
setTimeout(()=>musicButton.classList.add('show'),700);
function startMusic(){musicRequested=true;if(player?.playVideo){player.playVideo();musicPlaying=true;musicButton.classList.remove('paused');musicButton.setAttribute('aria-label','Выключить музыку');musicButton.querySelector('span').textContent='♫  Музыка играет'}}
function startOnFirstTouch(event){if(event.target.closest('#music-toggle'))return;startMusic();document.removeEventListener('pointerdown',startOnFirstTouch)}document.addEventListener('pointerdown',startOnFirstTouch);
musicButton.addEventListener('click',()=>{if(!player){musicRequested=true;return}if(musicPlaying){player.pauseVideo();musicPlaying=false;musicButton.classList.add('paused');musicButton.setAttribute('aria-label','Включить музыку');musicButton.querySelector('span').textContent='♫  Включить музыку'}else{startMusic()}});
const RSVP_ENDPOINT='https://script.google.com/macros/s/AKfycbxstCzVNOmMr-kMqp0V9XyxoUQdhKy_tmHO9EpXBBs3gAnGRa-ge0L7lXBObe8pyLc6/exec';
document.querySelector('#rsvp-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),name=data.get('name').trim().split(' ')[0],button=form.querySelector('button'),status=form.querySelector('.form-status');button.disabled=true;button.textContent='Отправляем…';status.textContent='';try{await fetch(RSVP_ENDPOINT,{method:'POST',mode:'no-cors',body:new URLSearchParams(data)});status.textContent=`${name}, спасибо! Ваш ответ отправлен ♡`;button.textContent='Ответ отправлен ✓';form.querySelectorAll('input').forEach(input=>input.disabled=true)}catch(error){status.textContent='Не удалось отправить ответ. Попробуйте ещё раз.';button.disabled=false;button.textContent='Отправить ответ →'}});
